"""empty message

Revision ID: 873173d2b133
Revises: 
Create Date: 2019-10-27 21:22:15.738902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873173d2b133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('producer', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_created'), 'products', ['created'], unique=False)
    op.create_index(op.f('ix_products_deleted'), 'products', ['deleted'], unique=False)
    op.create_index(op.f('ix_products_modified'), 'products', ['modified'], unique=False)
    op.create_index(op.f('ix_products_producer'), 'products', ['producer'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_producer'), table_name='products')
    op.drop_index(op.f('ix_products_modified'), table_name='products')
    op.drop_index(op.f('ix_products_deleted'), table_name='products')
    op.drop_index(op.f('ix_products_created'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
